tasks:
  - init: |
      docker pull container-registry.oracle.com/database/free 
      docker run -d -it --name 23cfree -p 1521:1521 -p 5500:5500 -p 8080:8080 -p 8443:8443 -e ORACLE_PWD=TheSuperSecret1509! container-registry.oracle.com/database/free:latest
      # open the readme.md document in VS code; note: thanks to the configuration in .vscode/settings.json, the document opens in markdown preview mode
      gp open README.md
      alias sql="/workspace/gitpod-oracle-database-23c-free/sqlcl/bin/sql"
      wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip && unzip -q sqlcl-latest.zip && 
      echo "done with download and unzip SQLcl and now sleep for 20 seconds until db is running" 
      sleep 20s &&       
      gp sync-done database-running &&
      touch db-running &&
      /workspace/gitpod-oracle-database-23c-free/sqlcl/bin/sql sys/"TheSuperSecret1509!"@localhost:1521/free as sysdba @"F1Data_Create_User.sql" && 
      /workspace/gitpod-oracle-database-23c-free/sqlcl/bin/sql f1data/"Formula1Database!"@localhost:1521/FREEPDB1 @"F1Data_setup-schema.sql" 
  - name: start container and run SQL*Plus session as user SYS
    init: gp sync-await database-running
    command: |
      docker start 23cfree   &&
      docker ps &&  
      sleep 3s && 
      echo "Oracle Database 23c Free is running. The database is accessible at localhost, port 1521; CDB database SID = FREE and has an additional user f1data/Formula1Database! in PDB FREEPDB1 " && 
      gp sync-done database-started &&
      docker exec -it 23cfree  sqlplus sys/TheSuperSecret1509! as sysdba
  - name: Open SQLcl for user f1data
    init: |
      gp sync-await database-running
    command: |
      gp sync-await database-started &&
      /workspace/gitpod-oracle-database-23c-free/sqlcl/bin/sql f1data/"Formula1Database!"@localhost:1521/FREEPDB1 

ports:

  # Oracle Database 23c Free
  - port: 1521
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - Oracle.oracledevtools